name: my_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pandas
  - numpy
  - pyarrow
  - psycopg2
  - sqlalchemy
  - jupyterlab
  - matplotlib
  - seaborn
  - pip
  - pip:
      - python-dotenv
      - gdown


